// このファイルは gen_registry.py により生成 (2026.06 時点の DB-Engines 上位＋著名DB)
// 手編集可。ステータス: Ga/Beta/PgCompatible/ReadOnly/Planned
use super::types::*;

/// 150件の対応DBレジストリ初期データ
pub fn seed() -> Vec<DbEntry> {
    vec![
        e("oracle", "Oracle", Category::Relational, Wire::Oracle, Status::Planned, MigrateVia::Dump),
        e("mysql", "MySQL", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("sqlserver", "Microsoft SQL Server", Category::Relational, Wire::Tds, Status::Planned, MigrateVia::Dump),
        e("postgresql", "PostgreSQL", Category::Relational, Wire::Postgres, Status::Ga, MigrateVia::PgWire),
        e("mongodb", "MongoDB", Category::Document, Wire::Mongo, Status::Planned, MigrateVia::Api),
        e("redis", "Redis", Category::KeyValue, Wire::Redis, Status::Planned, MigrateVia::Api),
        e("ibmdb2", "IBM Db2", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("elasticsearch", "Elasticsearch", Category::Search, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("sqlite", "SQLite", Category::Relational, Wire::File, Status::Beta, MigrateVia::File),
        e("msaccess", "Microsoft Access", Category::Relational, Wire::File, Status::Planned, MigrateVia::File),
        e("cassandra", "Apache Cassandra", Category::WideColumn, Wire::Cql, Status::Planned, MigrateVia::Api),
        e("mariadb", "MariaDB", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("snowflake", "Snowflake", Category::Relational, Wire::Proprietary, Status::ReadOnly, MigrateVia::Parquet),
        e("splunk", "Splunk", Category::Search, Wire::Http, Status::Planned, MigrateVia::Api),
        e("azuresql", "Microsoft Azure SQL Database", Category::Relational, Wire::Tds, Status::Planned, MigrateVia::Dump),
        e("hive", "Apache Hive", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("teradata", "Teradata", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("neo4j", "Neo4j", Category::Graph, Wire::Http, Status::Planned, MigrateVia::Api),
        e("saphana", "SAP HANA", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("filemaker", "FileMaker", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Api),
        e("solr", "Apache Solr", Category::Search, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("clickhouse", "ClickHouse", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("databricks", "Databricks", Category::Relational, Wire::Proprietary, Status::ReadOnly, MigrateVia::Parquet),
        e("firebase", "Firebase Realtime Database", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("dynamodb", "Amazon DynamoDB", Category::KeyValue, Wire::Http, Status::Planned, MigrateVia::Api),
        e("couchbase", "Couchbase", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("cockroachdb", "CockroachDB", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("influxdb", "InfluxDB", Category::TimeSeries, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("sapase", "SAP Adaptive Server", Category::Relational, Wire::Tds, Status::Planned, MigrateVia::Dump),
        e("memcached", "Memcached", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::None),
        e("vertica", "Vertica", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("trino", "Trino", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("presto", "Presto", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("bigquery", "Google BigQuery", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("redshift", "Amazon Redshift", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("dbase", "dBASE", Category::Relational, Wire::File, Status::Planned, MigrateVia::File),
        e("firebird", "Firebird", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("hbase", "Apache HBase", Category::WideColumn, Wire::Http, Status::Planned, MigrateVia::Api),
        e("aerospike", "Aerospike", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::Api),
        e("etcd", "etcd", Category::KeyValue, Wire::Http, Status::Planned, MigrateVia::Api),
        e("cosmosdb", "Microsoft Azure Cosmos DB", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("spanner", "Google Cloud Spanner", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Api),
        e("greenplum", "Greenplum", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("netezza", "IBM Netezza", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("informix", "IBM Informix", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("maxdb", "SAP MaxDB", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("realm", "Realm", Category::Document, Wire::File, Status::Planned, MigrateVia::File),
        e("riak", "Riak", Category::KeyValue, Wire::Http, Status::Planned, MigrateVia::Api),
        e("scylladb", "ScyllaDB", Category::WideColumn, Wire::Cql, Status::Planned, MigrateVia::Api),
        e("timescaledb", "TimescaleDB", Category::TimeSeries, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("tidb", "TiDB", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("yugabytedb", "YugabyteDB", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("singlestore", "SingleStore", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("duckdb", "DuckDB", Category::Relational, Wire::File, Status::Beta, MigrateVia::File),
        e("arangodb", "ArangoDB", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("opensearch", "OpenSearch", Category::Search, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("rethinkdb", "RethinkDB", Category::Document, Wire::Other, Status::Planned, MigrateVia::Api),
        e("orientdb", "OrientDB", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("ravendb", "RavenDB", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("marklogic", "MarkLogic", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("vector_milvus", "Milvus", Category::Vector, Wire::Http, Status::Planned, MigrateVia::Api),
        e("vector_pinecone", "Pinecone", Category::Vector, Wire::Http, Status::Planned, MigrateVia::Api),
        e("vector_weaviate", "Weaviate", Category::Vector, Wire::Http, Status::Planned, MigrateVia::Api),
        e("vector_qdrant", "Qdrant", Category::Vector, Wire::Http, Status::Planned, MigrateVia::Api),
        e("vector_chroma", "Chroma", Category::Vector, Wire::Http, Status::Planned, MigrateVia::Api),
        e("pgvector", "pgvector", Category::Vector, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("supabase", "Supabase", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("neon", "Neon", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("alloydb", "Google AlloyDB", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("citus", "Citus", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("materialize", "Materialize", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("risingwave", "RisingWave", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("questdb", "QuestDB", Category::TimeSeries, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("cratedb", "CrateDB", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("hydra", "Hydra", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("edgedb", "EdgeDB", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("tembo", "Tembo", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("paradedb", "ParadeDB", Category::Search, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("aurora_pg", "Amazon Aurora PostgreSQL", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("aurora_mysql", "Amazon Aurora MySQL", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("rds_mysql", "Amazon RDS MySQL", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("cloudsql_pg", "Google Cloud SQL (PostgreSQL)", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("percona", "Percona Server", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("vitess", "Vitess", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("memsql", "MemSQL", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("oceanbase", "OceanBase", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("polardb", "Alibaba PolarDB", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("gaussdb", "Huawei GaussDB", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("opengauss", "openGauss", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("tdsql", "Tencent TDSQL", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("dameng", "Dameng (DM)", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("kingbase", "KingbaseES", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("gbase", "GBase", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("monetdb", "MonetDB", Category::Relational, Wire::Other, Status::Planned, MigrateVia::Dump),
        e("h2", "H2", Category::Relational, Wire::File, Status::Planned, MigrateVia::File),
        e("hsqldb", "HSQLDB", Category::Relational, Wire::File, Status::Planned, MigrateVia::File),
        e("derby", "Apache Derby", Category::Relational, Wire::Other, Status::Planned, MigrateVia::Dump),
        e("ingres", "Actian Ingres", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("actian_vector", "Actian Vector", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
        e("exasol", "Exasol", Category::Relational, Wire::Other, Status::ReadOnly, MigrateVia::Parquet),
        e("kdb", "kdb+", Category::TimeSeries, Wire::Proprietary, Status::Planned, MigrateVia::Api),
        e("druid", "Apache Druid", Category::TimeSeries, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("pinot", "Apache Pinot", Category::TimeSeries, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("victoriametrics", "VictoriaMetrics", Category::TimeSeries, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("prometheus", "Prometheus", Category::TimeSeries, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("graphite", "Graphite", Category::TimeSeries, Wire::Http, Status::Planned, MigrateVia::Api),
        e("opentsdb", "OpenTSDB", Category::TimeSeries, Wire::Http, Status::Planned, MigrateVia::Api),
        e("timescale_cloud", "Timescale Cloud", Category::TimeSeries, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("tdengine", "TDengine", Category::TimeSeries, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("dolt", "Dolt", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("doltgres", "DoltgreSQL", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("ydb", "YDB", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("immudb", "immudb", Category::Relational, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("tigerbeetle", "TigerBeetle", Category::Relational, Wire::Other, Status::Planned, MigrateVia::Api),
        e("surrealdb", "SurrealDB", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("fauna", "Fauna", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("planetscale", "PlanetScale", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("turso", "Turso", Category::Relational, Wire::File, Status::Beta, MigrateVia::File),
        e("libsql", "libSQL", Category::Relational, Wire::File, Status::Beta, MigrateVia::File),
        e("rocksdb", "RocksDB", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::None),
        e("leveldb", "LevelDB", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::None),
        e("lmdb", "LMDB", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::None),
        e("foundationdb", "FoundationDB", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::Api),
        e("tikv", "TiKV", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::Api),
        e("badger", "BadgerDB", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::None),
        e("sled", "sled", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::None),
        e("hazelcast", "Hazelcast", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::Api),
        e("ignite", "Apache Ignite", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::Api),
        e("dragonfly", "Dragonfly", Category::KeyValue, Wire::Redis, Status::Planned, MigrateVia::Api),
        e("keydb", "KeyDB", Category::KeyValue, Wire::Redis, Status::Planned, MigrateVia::Api),
        e("valkey", "Valkey", Category::KeyValue, Wire::Redis, Status::Planned, MigrateVia::Api),
        e("tarantool", "Tarantool", Category::KeyValue, Wire::Other, Status::Planned, MigrateVia::Api),
        e("janusgraph", "JanusGraph", Category::Graph, Wire::Http, Status::Planned, MigrateVia::Api),
        e("tigergraph", "TigerGraph", Category::Graph, Wire::Http, Status::Planned, MigrateVia::Api),
        e("dgraph", "Dgraph", Category::Graph, Wire::Http, Status::Planned, MigrateVia::Api),
        e("nebula", "NebulaGraph", Category::Graph, Wire::Other, Status::Planned, MigrateVia::Api),
        e("memgraph", "Memgraph", Category::Graph, Wire::Http, Status::Planned, MigrateVia::Api),
        e("amazon_neptune", "Amazon Neptune", Category::Graph, Wire::Http, Status::Planned, MigrateVia::Api),
        e("typesense", "Typesense", Category::Search, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("meilisearch", "Meilisearch", Category::Search, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("manticore", "Manticore Search", Category::Search, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("sphinx", "Sphinx", Category::Search, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("algolia", "Algolia", Category::Search, Wire::Http, Status::Planned, MigrateVia::Api),
        e("couchdb", "Apache CouchDB", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("pouchdb", "PouchDB", Category::Document, Wire::File, Status::Planned, MigrateVia::File),
        e("ferretdb", "FerretDB", Category::Document, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("documentdb", "Amazon DocumentDB", Category::Document, Wire::Mongo, Status::Planned, MigrateVia::Api),
        e("ravendb_cloud", "RavenDB Cloud", Category::Document, Wire::Http, Status::Planned, MigrateVia::Api),
        e("objectbox", "ObjectBox", Category::Document, Wire::File, Status::Planned, MigrateVia::File),
        e("influxdb3", "InfluxDB 3.0", Category::TimeSeries, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("greptimedb", "GreptimeDB", Category::TimeSeries, Wire::Postgres, Status::PgCompatible, MigrateVia::PgWire),
        e("starrocks", "StarRocks", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("doris", "Apache Doris", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("databend", "Databend", Category::Relational, Wire::MySQL, Status::Beta, MigrateVia::MySqlWire),
        e("firebolt", "Firebolt", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("motherduck", "MotherDuck", Category::Relational, Wire::File, Status::Beta, MigrateVia::File),
        e("clickhouse_cloud", "ClickHouse Cloud", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Parquet),
        e("rockset", "Rockset", Category::Relational, Wire::Http, Status::ReadOnly, MigrateVia::Api),
        e("sap_iq", "SAP IQ", Category::Relational, Wire::Proprietary, Status::Planned, MigrateVia::Dump),
    ]
}

fn e(id: &str, name: &str, category: Category, wire: Wire, status: Status, migrate: MigrateVia) -> DbEntry {
    DbEntry {
        id: id.to_string(),
        name: name.to_string(),
        category,
        wire,
        status,
        migrate,
        backup: BackupSupport::from_migrate(migrate),
        rank: None,
        score: None,
        updated_at: None,
    }
}
